name: Add Release Team to PR

on:
  pull_request:
    types: [opened]
    branches:
      - 'release-**'

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    if: |
      ${{ github.actor }} != "elijah-dangerfield"
    steps:
      - name: Add Release Team Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: elijah-dangerfield
          re-request-when-approved: true
          re-request-when-changes-requested: true