name: Add Release Team As Reviewer

on:
  pull_request:
    types: [opened]
    branches:
      - 'release-**'

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Release Team As Reviewer
        run: ./scripts/add_release_team_reviewers.main.kts ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.number }}
