name: Add Release Team to PR

on:
  pull_request:
    types: [opened]
    branches:
      - 'release-**'

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.pull_request.user.login,'test') &&
      !contains(github.event.pull_request.user.login,'rock')
    steps:
      - name: Add Release Team Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: eli.dangerfield
          re-request-when-approved: true
          re-request-when-changes-requested: true